version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  django:
    build: .
    container_name: django-app
    depends_on:
      - redis
    ports:
      - "8001:8001"
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx  # Specify your custom Dockerfile here
    container_name: nginx
    depends_on:
      - django
    ports:
      - "8080:80"  # Exposing port 80 for Nginx
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
