FROM nginx:latest

# Remove the default Nginx configuration
RUN rm /etc/nginx/conf.d/default.conf

# Create directories for sites-available and sites-enabled
RUN mkdir -p /opt/status-page/nginx/static /etc/nginx/sites-available /etc/nginx/sites-enabled

# Copy your custom Nginx configuration file into sites-available
COPY ./status-page.conf /etc/nginx/sites-available/status-page.conf

# Copy static files
COPY ./statuspage/static /opt/status-page/nginx/static

# Symlink the configuration to sites-enabled
RUN ln -s /etc/nginx/sites-available/status-page.conf /etc/nginx/sites-enabled/status-page.conf

# Copy SSL certificate and key into the container from the 'certs' directory
COPY ./certs/status-page.crt /etc/ssl/certs/status-page.crt
COPY ./certs/status-page.key /etc/ssl/private/status-page.key

# Set proper permissions for the certificate and key
RUN chmod 600 /etc/ssl/private/status-page.key && \
    chmod 644 /etc/ssl/certs/status-page.crt

# Expose port 80 for HTTP and port 443 for HTTPS
EXPOSE 80 443
